### ISSUE TITLE
The target named "foo" has C++ sources that may use modules, but modules   are not supported by this generator

### ISSUE THREAD

**Issue by lukipedio** [matiassimon/cmake-modules-example#1]
When I try this example with devcontainer, I get the following error:

![image](https://github.com/matiassimon/cmake-modules-example/assets/16959881/a9f5355b-9242-4c2c-be27-b4b38e3ca693)

**Comment by matiassimon** [comment]
Hi Luca! The problem is that the default CMake generator seems to be Makefile, but modules require Ninja or Visual Studio Generators. I've just added the some envs in the dockerfile to fix it (commit 8fe80a8). I wasn't having that problem because I was using the CMake extension, which seems to use Ninja by default.
